parameters:
    u58_extended_attribute_type.attribute_type.features.class: U58\Bundle\ExtendedAttributeTypeBundle\AttributeType\FeaturesType
    u58_extended_attribute_type.attribute_type.image_collection.class: U58\Bundle\ExtendedAttributeTypeBundle\AttributeType\ImageCollectionType
    u58_extended_attribute_type.attribute_type.youtube.class: U58\Bundle\ExtendedAttributeTypeBundle\AttributeType\YoutubeType
    u58_extended_attribute_type.attribute_type.country.class: U58\Bundle\ExtendedAttributeTypeBundle\AttributeType\CountryType

services:
    u58_extended_attribute_type.attribute_type.features:
        class: '%u58_extended_attribute_type.attribute_type.features.class%'
        arguments:
            - features
        tags:
            - { name: pim_catalog.attribute_type, alias: u58_catalog_features, entity: '%pim_catalog.entity.product.class%' }

    u58_extended_attribute_type.attribute_type.image_collection:
        class: '%u58_extended_attribute_type.attribute_type.image_collection.class%'
        arguments:
            - images
        tags:
            - { name: pim_catalog.attribute_type, alias: u58_catalog_image_collection, entity: '%pim_catalog.entity.product.class%' }

    u58_extended_attribute_type.attribute_type.youtube:
        class: '%u58_extended_attribute_type.attribute_type.youtube.class%'
        arguments:
            - youtube
        tags:
            - { name: pim_catalog.attribute_type, alias: u58_catalog_youtube, entity: '%pim_catalog.entity.product.class%' }

    u58_extended_attribute_type.attribute_type.country:
        class: '%u58_extended_attribute_type.attribute_type.country.class%'
        arguments:
            - youtube
        tags:
            - { name: pim_catalog.attribute_type, alias: u58_catalog_country, entity: '%pim_catalog.entity.product.class%' }
