parameters:
    u58_catalog.comparator.attribute.array.class: U58\Bundle\ExtendedAttributeTypeBundle\Comparator\Attribute\ArrayComparator
    #u58_catalog.comparator.attribute.features.class: U58\Bundle\ExtendedAttributeTypeBundle\Comparator\Attribute\FeaturesComparator
    #u58_catalog.comparator.attribute.image_collection.class: U58\Bundle\ExtendedAttributeTypeBundle\Comparator\Attribute\ImageCollectionComparator

services:
    u58_catalog.comparator.attribute.array:
        class: '%u58_catalog.comparator.attribute.array.class%'
        arguments:
            - ['u58_catalog_features', 'u58_catalog_image_collection']
        tags:
            - { name: pim_catalog.attribute.comparator }

    u58_catalog.comparator.attribute.scalar:
        class: '%pim_catalog.comparator.attribute.scalar.class%'
        arguments:
            - ['u58_catalog_youtube', 'u58_catalog_country']
        tags:
            - { name: pim_catalog.attribute.comparator, priority: -128 }

    #u58_catalog.comparator.attribute.features:
    #    class: '%u58_catalog.comparator.attribute.features.class%'
    #    arguments:
    #        - ['u58_catalog_features']
    #        - '@akeneo_file_storage.repository.file_info'
    #    tags:
    #        - { name: pim_catalog.attribute.comparator }

    #u58_catalog.comparator.attribute.image_collection:
    #    class: '%u58_catalog.comparator.attribute.image_collection.class%'
    #    arguments:
    #        - ['u58_catalog_image_collection']
    #    tags:
    #        - { name: pim_catalog.attribute.comparator }
