extensions:
    u58-attribute-form-image-collection:
        module: pim/common/simple-view
        config:
            template: pim/template/common/drop-zone

    u58-attribute-form-image-collection-validation-params:
        module: pim/common/simple-view
        parent: u58-attribute-form-image-collection
        targetZone: content
        position: 110
        config:
            template: pim/template/form/tab/section
            templateParams:
                sectionTitle: pim_enrich.form.attribute.tab.properties.section.validation
                dropZone: content

    u58-attribute-form-image-collection-validation-params-number-min:
        module: pim/form/common/fields/text
        parent: u58-attribute-form-image-collection-validation-params
        targetZone: content
        position: 100
        config:
            fieldName: number_min
            label: pim_enrich.form.attribute.tab.properties.label.number_min

    u58-attribute-form-image-collection-validation-params-number-max:
        module: pim/form/common/fields/text
        parent: u58-attribute-form-image-collection-validation-params
        targetZone: content
        position: 100
        config:
            fieldName: number_max
            label: pim_enrich.form.attribute.tab.properties.label.number_max

    u58-attribute-form-image-collection-validation-params-allowed-extensions:
        module: pim/form/common/fields/select
        parent: u58-attribute-form-image-collection-validation-params
        targetZone: content
        position: 120
        config:
            fieldName: allowed_extensions
            label: pim_enrich.form.attribute.tab.properties.label.allowed_extensions
            choices: '%pim_catalog_image_allowed_extensions%'
            isMultiple: true
            defaultValue: [jpeg, jpg]

    u58-attribute-form-image-collection-validation-params-max-file-size:
        module: pim/form/common/fields/text
        parent: u58-attribute-form-image-collection-validation-params
        targetZone: content
        position: 130
        config:
            fieldName: max_file_size
            label: pim_enrich.form.attribute.tab.properties.label.max_file_size
